In [1]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer , WordNetLemmatizer
import pandas as pd
import re
import matplotlib.pyplot as plt
import spacy

In [2]:
bbc_data = pd.read_csv("bbc_news.csv")

In [3]:
bbc_data.head()

,Unnamed: 0,index,title,pubDate,guid,link,description
0,0,6684,Can I refuse to work?,"Wed, 10 Aug 2022 15:46:18 GMT",https://www.bbc.co.uk/news/business-62147992,https://www.bbc.co.uk/news/business-62147992?a...,With much of the UK enduring another period of...
1,1,9267,'Liz Truss the Brief?' World reacts to UK poli...,"Mon, 17 Oct 2022 11:35:12 GMT",https://www.bbc.co.uk/news/world-63285480,https://www.bbc.co.uk/news/world-63285480?at_m...,The UK's political chaos has been watched arou...
2,2,7387,Rationing energy is nothing new for off-grid c...,"Wed, 31 Aug 2022 05:20:18 GMT",https://www.bbc.co.uk/news/uk-scotland-highlan...,https://www.bbc.co.uk/news/uk-scotland-highlan...,Scoraig in the north west Highlands has long h...
3,3,767,The hunt for superyachts of sanctioned Russian...,"Tue, 22 Mar 2022 14:37:01 GMT",https://www.bbc.co.uk/news/60739336,https://www.bbc.co.uk/news/60739336?at_medium=...,"Wealthy Russians sanctioned by the US, EU and ..."
4,4,3712,Platinum Jubilee: 70 years of the Queen in 70 ...,"Wed, 01 Jun 2022 23:17:33 GMT",https://www.bbc.co.uk/news/uk-61660128,https://www.bbc.co.uk/news/uk-61660128?at_medi...,A quick look back at the Queen's 70 years on t...

In [14]:
bbc_data_titles = pd.DataFrame(bbc_data['title'])

In [15]:
print(type(bbc_data_titles))

<class 'pandas.core.frame.DataFrame'>

In [16]:
bbc_data_titles.head()

                                               title
0                              Can I refuse to work?
1  'Liz Truss the Brief?' World reacts to UK poli...
2  Rationing energy is nothing new for off-grid c...
3  The hunt for superyachts of sanctioned Russian...
4  Platinum Jubilee: 70 years of the Queen in 70 ...

In [17]:
bbc_data_titles["lower_case_title"] = bbc_data_titles['title'].str.lower()

In [18]:
bbc_data_titles.head()

,title,lower_case_title
0,Can I refuse to work?,can i refuse to work?
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...

In [19]:
en_stopwords = stopwords.words('english')

In [20]:
bbc_data_titles['titles_no_stopwords'] = bbc_data_titles['title'].apply(lambda x: ' '.join([word for word in x.split() if word not in en_stopwords]))

In [21]:
bbc_data_titles["title_no_stopwords_no_punct"] = bbc_data_titles['titles_no_stopwords'].apply(lambda x : re.sub(r"[^\w\s]" , "" , x))

In [22]:
bbc_data_titles["token_raw"] = bbc_data_titles['title'].apply(lambda x: word_tokenize(x))

In [23]:
bbc_data_titles["token_clean"] = bbc_data_titles['title_no_stopwords_no_punct'].apply(lambda x: word_tokenize(x))

In [24]:
bbc_data_titles.head()

,title,lower_case_title,titles_no_stopwords,title_no_stopwords_no_punct,token_raw,token_clean
0,Can I refuse to work?,can i refuse to work?,Can I refuse work?,Can I refuse work,"[Can, I, refuse, to, work, ?]","[Can, I, refuse, work]"
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...,'Liz Truss Brief?' World reacts UK political t...,Liz Truss Brief World reacts UK political turmoil,"['Liz, Truss, the, Brief, ?, ', World, reacts,...","[Liz, Truss, Brief, World, reacts, UK, politic..."
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...,Rationing energy nothing new off-grid community,Rationing energy nothing new offgrid community,"[Rationing, energy, is, nothing, new, for, off...","[Rationing, energy, nothing, new, offgrid, com..."
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...,The hunt superyachts sanctioned Russian oligarchs,The hunt superyachts sanctioned Russian oligarchs,"[The, hunt, for, superyachts, of, sanctioned, ...","[The, hunt, superyachts, sanctioned, Russian, ..."
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...,Platinum Jubilee: 70 years Queen 70 seconds,Platinum Jubilee 70 years Queen 70 seconds,"[Platinum, Jubilee, :, 70, years, of, the, Que...","[Platinum, Jubilee, 70, years, Queen, 70, seco..."

In [25]:
lemmatizer = WordNetLemmatizer()

In [26]:
bbc_data_titles["token_clean_lemmatized"] = bbc_data_titles['token_clean'].apply(lambda x : [lemmatizer.lemmatize(word)for word in x])

In [27]:
token_raw_list = sum(bbc_data_titles['token_raw'] , [])
token_clean_list = sum(bbc_data_titles['token_clean_lemmatized'] , [])

pos

In [28]:
nlp = spacy.load('en_core_web_sm')

In [29]:
doc = nlp(' '.join(token_raw_list))

In [30]:
pos_df = pd.DataFrame(columns=['token' , 'pos_tag'])

In [ ]:
for token in doc:
    pos_df = pd.concat([pos_df , pd.DataFrame.from_records([{'token' : token.text , 'pos_tag' : token.pos_}])] ,ignore_index=True)

In [33]:
pos_df_counts = pos_df.groupby(['token' , 'pos_tag']).size().reset_index(name='counts').sort_values(by='counts',ascending=False)
pos_df_counts.head(10)

     token pos_tag  counts
95       :   PUNCT     543
8        '   PUNCT     300
2897    in     ADP     187
4082    to    PART     175
3268    of     ADP     172
22       -   PUNCT     166
4043   the     DET     163
1856   and   CCONJ     147
15      's    PART     143
97       ?   PUNCT     130

In [35]:
noun = pos_df_counts[pos_df_counts.pos_tag == 'NOUN'][:10]
noun

       token pos_tag  counts
4267     war    NOUN      35
3552  record    NOUN      15
3416  police    NOUN      14
4356    year    NOUN      14
4316     win    NOUN      14
3061  living    NOUN      13
4009     tax    NOUN      13
2326     day    NOUN      12
3368  people    NOUN      12
2031    boss    NOUN      11

In [36]:
verb = pos_df_counts[pos_df_counts.pos_tag == 'VERB'][:10]
verb

       token pos_tag  counts
3687    says    VERB      30
9          '    VERB      14
2670   found    VERB      13
4317     win    VERB      12
4324    wins    VERB      10
2713     get    VERB       9
2388    dies    VERB       9
3990    take    VERB       8
2982  killed    VERB       8
3686     say    VERB       8

ner

In [46]:
ner_df = pd.DataFrame(columns=['token' , 'ner_tag'])

In [47]:
for token in doc.ents:
    if pd.isna(token.label_) is False:
        ner_df = pd.concat([ner_df , pd.DataFrame.from_records([{'token' : token.text , 'ner_tag' : token.label_}])] ,ignore_index=True)

In [48]:
ner_df.head()

         token   ner_tag
0    Liz Truss    PERSON
1           UK       GPE
2    Rationing   PRODUCT
3  superyachts  CARDINAL
4      Russian      NORP

In [50]:
ner_df_counts = ner_df.groupby(['token' , 'ner_tag']).size().reset_index(name='counts').sort_values(by='counts',ascending=False)
ner_df_counts.head(10)

               token      ner_tag  counts
965          Ukraine          GPE      47
955               UK          GPE      36
329          England          GPE      32
819          Russian         NORP      20
957               US          GPE      19
1031  World Cup 2022        EVENT      18
1058           first      ORDINAL      13
918       The Papers  WORK_OF_ART      13
378           France          GPE      12
226            China          GPE      11